### ISSUE TITLE
[Question] How long does it take to train a round?

### ISSUE THREAD

**Issue by Chris-Chow** [columbia-ai-robotics/scalingup#11]
How long does it take you guys to train and generate datas? I seem to spend a lot of time on training, a training round takes about 5-8h with a single A100 GPU. Besides, it's also takes me too long for the data generation phase?When I run this code:

`python scalingup/inference.py evaluation.num_episodes=50000 policy=scalingup evaluation=drawer `

It seems to cost me many days to finish this process. I don't know if this is due to a misconfiguration or action on my part, or if this is just the norm.

My CPU is Intel(R) Xeon(R) Gold 6314U CPU @ 2.30GHz, and GPUs are A100s.

Best Regards!

**Comment by wangyan-hlab** [comment]
Hi,
@Chris-Chow 

FYI:
I am training on a single RTX3090 GPU and the CPU is Intel Core i5-10500 @ 3.1GHz.

For the data generation, it took me about 12h to generate 500 trajectories of bin_transport_train.
The command I ran:
```python scalingup/inference.py evaluation.num_episodes=500 policy=scalingup evaluation=bin_transport_train evaluation/env/domain_rand_config=all evaluation.env.domain_rand_config.dtd_root=/home/$USER/Documents/scalingup/scalingup num_processes=1```

For the training process, it took me about 3 days to train 10 epochs (5000 per epoch). Specifically, about 6.5h for training ONE epoch and about 1h for evaluating after EACH epoch.
The command I ran:
```python scalingup/train.py dataset_path=path/to/dataset evaluation=bin_transport_test algo=diffusion_default algo.replay_buffer.batch_size=256 algo.replay_buffer.num_steps_per_update=5000 trainer.max_epochs=10 num_processes=8```

Hope the informatin help.

**Comment by huy-ha** [comment]
@wangyan-hlab 's command uses only a single process for data generation, but you can increase `num_processes` if your system has enough CPU and RAM.

With 256 CPU cores and `num_processes=256`, data generation for bin transport takes about 15 minutes. When I was [profiling line-by-line](https://github.com/columbia-ai-robotics/scalingup/blob/master/docs/extend.md#profiling-%EF%B8%8F), I found that [producing point-clouds](https://github.com/columbia-ai-robotics/scalingup/blob/master/scalingup/utils/core.py#L3374-L3379) for the grasp & placement sampler was one of the biggest bottlenecks. You can reduce `MAX_OFFSCREEN_HEIGHT` and make sure `<global offwidth="MAX_OFFSCREEN_HEIGHT" offheight="MAX_OFFSCREEN_HEIGHT"/>` matches, which would produce lower resolution point clouds but be faster. The caveat is if the point cloud resolution is too low, it might miss small detailed geometry.

For training, my experience matches with @wangyan-hlab . Some tips which can improve training:
 - torch compiling will train about 1.5-2x faster. However, RoboMimic's encoder currently has some code which can't be torch compiled, so working around that by using a ResNet encoder instead ( `algo/state_sequence_encoder/vision_encoder=image_resnet`) should directly allow you to torch compile the model.
 - evaluation is currently quite costly, so you could disable or use a small number of evaluation episodes (`evaluation.num_episodes=2`) during training, and evaluate your checkpoints later.

**Comment by Chris-Chow** [comment]
@huy-ha Thanks for your answer! Another condition is that I found that when I trained the usages of cpus and gpus were all low, which just seemed like the usual. I'd like to ask if this is normal. 

Besides I find that in your docs you [data generate](https://github.com/columbia-ai-robotics/scalingup/blob/master/docs/reproduce.md#data-generation-for-training) you generate 50000 trajectories, which is a large number. So I want to ask how many trajectories or point-cloud data are "enough" you guys think to train a diffusion poclicy.

**Comment by huy-ha** [comment]
> Another condition is that I found that when I trained the usages of cpus and gpus were all low

Utilization of GPU should be high during training, but CPU should be low. During eval, both is lower than I would like, and the bottleneck is in that GPU inference is not batched. You can also disable evaluation or make it shorter during training by using setting `evaluation.num_episodes` accordingly.

Here's [a script](https://github.com/columbia-ai-robotics/scalingup/files/12539948/test_diffusion.zip)  I used to debug these issues. You can use [line profiler](https://github.com/pyutils/line_profiler) around each of these functions to test for data loading speed, GPU utilization in the best case (no data loading I/O) and identify the bottleneck.

During data generation, your CPU utilization should be 100%. During training, your GPU utilization should hover above 90%.

> So I want to ask how many trajectories or point-cloud data are "enough" you guys think to train a diffusion poclicy

I set the number to be 50000 in the documentation because not all trajectories generated are successful (which [aren't saved to disk](https://github.com/columbia-ai-robotics/scalingup/blob/master/scalingup/config/evaluation/sampler_config/default.yaml#L13)). You can `ctrl+c` the data generation once you have enough.

How much data is enough likely depends on the task, and I have not experimented varying dataset size.

**Comment by whc688** [comment]
Hi,@huy-ha 
![image](https://github.com/real-stanford/scalingup/assets/72799643/f2fc3f2f-ebed-45e5-b3bb-320129043827)
Your work is really excellent! I'm not quite sure about one thing, though. Were the 'Distill Ours' and 'Distill No Retry' models for each domain trained on datasets with 500 successful trajectories?
