### ISSUE TITLE
[Questions]How many trajectories are used to train?

### ISSUE THREAD

**Issue by whc688** [columbia-ai-robotics/scalingup#16]
Hi,@huy-ha 
![image](https://github.com/real-stanford/scalingup/assets/72799643/1488be53-ca18-48ef-9f9d-087a287060b5)
Your work is really excellent! I'm not quite sure about one thing, though. Were the 'Distill Ours' and 'Distill No Retry' models for each domain trained on datasets with 500 successful trajectories?

**Comment by huy-ha** [comment]
Hey! Thanks for the kind words.

They were all trained using at least 500 successful trajectories, but some of them were trained on more. For instance, for the short-horizon transport domain, it was very fast to generate a lot of data, so both `Distill No Retry` and `Distill Ours` were trained on more data than other domains. Qualitatively, `Distill No Retry` would occasionally fail, but never retried failed tasks, leading to much lower success rates. This failure is more common in more challenging domains, either due to precision of placements (catapult), novel geometry (transport), and long horizon (drawer). For mailbox, there were no successful trajectories which contained no subtask failures, so we've reported zero for `Distill No Retry` in the mailbox domain.

**Comment by whc688** [comment]
Thank you for your reply！

So, if I understand correctly, you generate 50,000 trajectories for each domain and filter out the ones that fail. The number of successful trajectories remaining for each domain varies (with a minimum of 500). Then, you use all of these successful trajectories for training. Is my understanding correct?
