### ISSUE TITLE
The model `text-davinci-003` has been deprecated

### ISSUE THREAD

**Issue by cookiescoo** [columbia-ai-robotics/scalingup#23]
Hello，thank you for sharing this amazing work!
I try to run the scalingup-master/examples/exploration_task_tree.py .However, I I met the error:
openai.error.InvalidRequestError: The model `text-davinci-003` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations

Then I change `text-davinci-003` into 'gpt-3.5-turbo-instruct' ,but it says:
openai.error.InvalidRequestError: Setting 'echo' and 'logprobs' at the same time is not supported for this model.

Please give some help .Thanks!

**Comment by cucu9999** [comment]
sure, i have the same problem. hope your help!

**Comment by huy-ha** [comment]
Hey! Unfortunately, OpenAI API updated their pip package since this work was released. There should be two steps involved. 
 - First, you can replace the contents of the [`complete`](https://github.com/real-stanford/scalingup/blob/master/scalingup/utils/openai_api.py#L351-L357) method used to any other LLM API you want (or the latest OpenAI API), and remove logprobs where it appears, such as in [`GPT3Completion`](https://github.com/real-stanford/scalingup/blob/master/scalingup/utils/openai_api.py#L54-L72). 
 - Second, the [LLM multiple choice completion step](https://github.com/real-stanford/scalingup/blob/master/scalingup/policy/llm_policy_utils.py#L137-L193) depends on logprobs. This helps in LLM completion performance when it's a multiple choice query. However, the only class which uses it is the [PickAndPlace](https://github.com/real-stanford/scalingup/blob/master/scalingup/policy/llm_policy_utils.py#L230) parser, so you can update it's definition to inherit from `LLMCompletionStep` instead.
 
 Hope this helps!
