### ISSUE TITLE
training stuck after the first epoch

### ISSUE THREAD

**Issue by yellow07200** [columbia-ai-robotics/scalingup#8]
hi, 

`python scalingup/train.py dataset_path=/media/HDD4/dataset/files evaluation=drawer algo=diffusion_default algo.replay_buffer.batch_size=128 evaluation.num_episodes=1
`
I try to train the model, but it always stucks in the second epoch as shown in the sceenshot below.
 
![Screenshot from 2023-08-22 14-49-38](https://github.com/columbia-ai-robotics/scalingup/assets/51048754/01cd5686-0a4f-4e62-b7ed-116ab17d43c8)

need your help, many thanks!

**Comment by wangyan-hlab** [comment]
Hi,
 
I used to get stuck because of the high usage of memory during the evaluation stage after each epoch.
Would you please monitor your usage of memory (e.g., on the wandb website)?

If it is very high, I think you may resolve the problem by adding ```num_processes=$INTNUM``` to your command to reduce the process number as the default value seems to be 20.
For me, $INTNUM=8 works well, but you can try more different numbers according to your device.

Hope this may help~

**Comment by wangyan-hlab** [comment]
> hi,
> 
> `python scalingup/train.py dataset_path=/media/HDD4/dataset/files evaluation=drawer algo=diffusion_default algo.replay_buffer.batch_size=128 evaluation.num_episodes=1 ` I try to train the model, but it always stucks in the second epoch as shown in the sceenshot below.
> 
> ![Screenshot from 2023-08-22 14-49-38](https://user-images.githubusercontent.com/51048754/262327961-01cd5686-0a4f-4e62-b7ed-116ab17d43c8.png)
> 
> need your help, many thanks!

@yellow07200 
Hi,

I used to get stuck because of the high usage of memory during the evaluation stage after each epoch.
Would you please monitor your usage of memory (e.g., on the wandb website)?

If it is very high, I think you may resolve the problem by adding num_processes=$INTNUM to your command to reduce the process number as the default value seems to be 20.
For me, $INTNUM=8 works well, but you can try more different numbers according to your device.

Hope this may help~

**Comment by yellow07200** [comment]
>Hi,
>
>I used to get stuck because of the high usage of memory during the evaluation stage after each epoch.
>Would you please monitor your usage of memory (e.g., on the wandb website)?
>
>If it is very high, I think you may resolve the problem by adding num_processes=$INTNUM to your command to reduce the >process number as the default value seems to be 20.
>For me, $INTNUM=8 works well, but you can try more different numbers according to your device.
>
>Hope this may help~


Hi @wangyan-hlab 
Thanks for your suggestion. I checked out the GPU usage using `num_process=1`, but it still stuck at epoch_2. The figure below is the chart of GPU usage when `num_process=2`.
![GPU all](https://github.com/columbia-ai-robotics/scalingup/assets/51048754/ad387963-00f8-4748-b7e5-cbe9c0588197)
It seems the usage of memory is not high. 

I also observed the code is stuck in the while loop of `ray/_private/log_monitor.py` 

![log_monitor](https://github.com/columbia-ai-robotics/scalingup/assets/51048754/bd3de513-c82d-4c27-9e5d-af34b782f6f0)

Did you ever run into this issue?

**Comment by wangyan-hlab** [comment]
> > Hi,
> > I used to get stuck because of the high usage of memory during the evaluation stage after each epoch.
> > Would you please monitor your usage of memory (e.g., on the wandb website)?
> > If it is very high, I think you may resolve the problem by adding num_processes=$INTNUM to your command to reduce the >process number as the default value seems to be 20.
> > For me, $INTNUM=8 works well, but you can try more different numbers according to your device.
> > Hope this may help~
> 
> Hi @wangyan-hlab Thanks for your suggestion. I checked out the GPU usage using `num_process=1`, but it still stuck at epoch_2. The figure below is the chart of GPU usage when `num_process=2`. ![GPU all](https://user-images.githubusercontent.com/51048754/262562842-ad387963-00f8-4748-b7e5-cbe9c0588197.png) It seems the usage of memory is not high.
> 
> I also observed the code is stuck in the while loop of `ray/_private/log_monitor.py`
> 
> ![log_monitor](https://user-images.githubusercontent.com/51048754/262563395-bd3de513-c82d-4c27-9e5d-af34b782f6f0.png)
> 
> Did you ever run into this issue?

Hi, 

@yellow07200 
1. the usage of memory
Have you checked this chart? It's the 19th under the **System** item. You can see that the evaluation process occupies almost 90% of the memory. But since you have set ```num_processes``` to the least and the stuck still happens, I am sorry that I have no idea how to fix it. Note that it's **num_processes**, not **num_process**.
<img width="454" alt="image" src="https://github.com/columbia-ai-robotics/scalingup/assets/45218434/48ba6ac3-0220-4bac-a9a2-a882fca675b2">

2. I am sorry that I haven't met the issue _stuck in the while loop of `ray/_private/log_monitor.py`_.

**Comment by yellow07200** [comment]
> Hi,
> 
> @yellow07200
> 
> 1. the usage of memory
>    Have you checked this chart? It's the 19th under the **System** item. You can see that the evaluation process occupies almost 90% of the memory. But since you have set `num_processes` to the least and the stuck still happens, I am sorry that I have no idea how to fix it. Note that it's **num_processes**, not **num_process**.
> 
> <img alt="image" width="454" src="https://user-images.githubusercontent.com/45218434/262571595-48ba6ac3-0220-4bac-a9a2-a882fca675b2.png">
> 2. I am sorry that I haven't met the issue _stuck in the while loop of `ray/_private/log_monitor.py`_.

Hi, 

It keeps showing errors caused from site-packages files when I debug my code deeply line by line.
But when I run the original code, it's training successfully~~~ It's a bit weird, because I only add a new robot environment.  

Anyway, it's training finally. Thanks for your help!

Best regards

**Comment by huy-ha** [comment]
@yellow07200 From your original screenshot, "Reducer buckets have been built ..." suggests you are using multigpu? I think that's actually the reason why training halted. The evaluation policy used only one of the GPUs in your multigpu training, so when epoch 2 started, all other GPUs (that weren't used for evaluation at the end of epoch 1) were waiting for their batches. 

Let me know if it still happens if you use single GPU!

**Comment by yangsizhe** [comment]
@huy-ha hi, so the code do not support multigpu, right?

**Comment by huy-ha** [comment]
Yep, but, if you're willing to run training without evaluation (by removing the [evaluation callback](https://github.com/real-stanford/scalingup/blob/master/scalingup/train.py#L97) and returning immediately at the beginning of the [validation step](https://github.com/real-stanford/scalingup/blob/master/scalingup/algo/diffusion.py#L676-L728)) then I think multi-gpu training should work.

**Comment by Louis-ZhangLe** [comment]
> Yep, but, if you're willing to run training without evaluation (by removing the [evaluation callback](https://github.com/real-stanford/scalingup/blob/master/scalingup/train.py#L97) and returning immediately at the beginning of the [validation step](https://github.com/real-stanford/scalingup/blob/master/scalingup/algo/diffusion.py#L676-L728)) then I think multi-gpu training should work.

hello, I trained with multiple GPUs and reported an error after an epoch ended: "NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=103, OpType=BROADCAST, NumelIn=213, NumelOut=213, Timeout
(ms)=1800000) ran for 1800913 milliseconds before timing out.". I have removed the evaluation callback. I have set [on_train_epoch_end](https://github.com/real-stanford/scalingup/blob/master/scalingup/algo/diffusion.py#L624) function directly returns None. But there is still an error. Am I doing this right？Thanks.
